<?php
$static_title = 'Khronos OpenXR Registry';
include_once("../../assets/static_pages/khr_page_top.php");
?>

<p> The OpenXR registry contains formatted specifications of the OpenXR API,
    header files, API reference pages, the reference card, and related
    documentation. The registry also links to the GitHub repository where
    the sources for these documents can be found. </p>

<p> Index to the OpenXR Registry page content: </p>

<ul>
    <li> <a href="#apispecs"/> <b>OpenXR 0.90 API Provisional Specifications</b> </a> </li>
    <li> <a href="#refguide"/> <b>OpenXR 0.90 API Overview</b> </a> </li>
    <li> <a href="#refpages"/> <b>OpenXR API Reference Pages</b> </a> </li>
    <li> <a href="#repos"/> <b>OpenXR GitHub Repositories</b>
        <ul>
        <li> <a href="#repo-docs"/> <b>API and Extension Specification Repository</b> </a>
            <ul>
            <li> <a href="#headers"/> <b>Header Files</b> </a> </li>
            <li> <a href="#apiregistry"/> <b>API Registry</b> </a> </li>
            </ul> </li>
        <li> <a href="#repo-loader"/> <b>Loader and Validation Layers Repositories</b> </a> </li>
        <li> <a href="#repo-samples"/> <b>Sample Code Repository</b> </a> </li>
        </ul> </li>
</ul>


<h2> <a name="apispecs"></a> <b>OpenXR 0.90 API Provisional Specifications</b> </h2>

<p> We currently publish the OpenXR API Specification in PDF and HTML forms.
    There are several versions of the OpenXR 0.90 Specification, as well as
    related Specifications and collateral material: </p>

<ul>
<li> <b>OpenXR 0.90 Provisional API + Khronos-defined Extensions</b>
     <a href="specs/0.90/html/xrspec.html">(Single-file HTML)</a>
     <a href="specs/0.90/pdf/xrspec.pdf">(PDF)</a> </li>
     This Specification includes Khronos-defined <tt>KHR</tt> extensions
     such as the graphics API interfaces used on different platforms 
     and window systems. </li>
</ul>

<h2> <a name="refguide"></a> <b>OpenXR 0.90 API Overview</b> </h2>

<p> The <a href="specs/0.90/refguide/OpenXR-0.90-web.pdf">OpenXR 0.90 API 
    Overview (PDF)</a> is a compact document providing an overview of the 
    OpenXR 0.90 API, Input and Haptics, and a typical OpenXR app's flow.

<h2> <a name="refpages"></a> <b>API Reference Pages</b> </h2>

<p> The OpenXR API Reference Pages describe how to use individual API
    and extension commands. The goal is to define all commands and
    structures in the core API and extensions, although there may be some
    omissions. In addition to the format published here, it is possible to
    generate other formats from the reference page sources, such as PDF or
    Unix <tt>nroff</tt> man page sources.</p>

<ul>
<li> <b>OpenXR 0.90 Reference Pages</b>
     <a href="specs/0.90/man/html/">(HTML, one file per reference page)</a>
     </li>
</ul>

<p> The reference pages are generated by automatic extraction from the
    Specification source, and are not checked into GitHub. The set of pages
    linked above are generated from the 0.90 API specification including all
    extensions.</p>

<h2> <a name="repos"></a> <b> OpenXR GitHub Repositories </b> </h2>

<h3> <a name="repo-docs"></a> <b>API and Extension Specification Repository</b> </h3>

<p> The <a href="https://github.com/KhronosGroup/OpenXR-Docs">
    OpenXR-Docs</a> repository will contain the AsciiDoc source for the OpenXR
    API specification, and for registered OpenXR API extensions when
    the 1.0 specification is released. </p>

<p> OpenXR-Docs also contains the header files, API Registry, and
    reference page sources. </p>


<h4> <a name="headers"></a> <b>Header Files</b> </h4>

<p> For most developers, the header files provided with a loader and/or
    driver package, such as the one defined in the <a
    href="#repo-loader"> loader and validation layers</a> GitHub
    repository, are all that's needed. </p>

<p> However, all OpenXR headers provided by Khronos are ultimately obtained
    from the <a href="#repo-docs"> OpenXR-Docs</a> repository You may clone
    this repository and copy the headers from <b>include/openxr/*.h</b>;
    or, if you need to generate a customized version of the headers, use the
    <a href="#apiregistry">API Registry</a> and scripts under
    <b>xml/</b>. </p>


<h4> <a name="apiregistry"></a> <b>API Registry</b> </h4>

<p> OpenXR defines an API Registry for the API and extensions,
    formally defining command prototypes, structures, enumerants, and
    many other aspects of the API and extension mechanisms. The OpenXR
    Registry is used for many more purposes than most other Khronos API
    registries, and is the basis for generating the header files;
    AsciiDoc include files used in the Specification, and reference
    pages for interface definitions, parameter and member validity
    language, and synchronization language; and more. </p>

<h3> <a name="repo-loader"></a> <b>Loader and Validation Layers Repositories</b> </h3>

<p> There are additional Khronos Github repositories containing OpenXR
    source code, libraries, and tools. Originally this material was in the
    single &quot;OpenXR-SDK&quot; repository:

<ul>
<li> The <a href="https://github.com/KhronosGroup/OpenXR-SDK">
     OpenXR-SDK</a> repository contains the OpenXR loader that is used 
     for Linux, Windows, MacOS, and iOS, as well as validation layer,
     and sample code for example OpenXR applications. </li>
</ul>

<h3> <a name="repo-samples"></a> <b>Sample Code Repository</b> </h3>

<p> The <a href="https://github.com/KhronosGroup/OpenXR-SDK">
    OpenXR-SDK</a> repository contains sample code showing use of
    OpenXR, contributed by various Khronos members and other authors.
    </p>


<?php include_once("../../assets/static_pages/khr_page_bottom.php"); ?>
</body>
</html>
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
